### ISSUE TITLE
OAuth 2.0 Device Authorization Grant

### ISSUE THREAD

**Issue by asteven** [lepture/authlib#125]
Thanks for writing this wonderful library!
Do you think it would be difficult to add support for device flow?

https://datatracker.ietf.org/doc/draft-ietf-oauth-device-flow/
https://www.identityserver.com/articles/an-introduction-to-the-oauth-device-flow
https://www.ibm.com/blogs/security-identity-access/oauth-device-flows/

Someone wrote a proxy server in PHP which may be useful to investigate.
https://github.com/aaronpk/Device-Flow-Proxy-Server

**Comment by lepture** [comment]
You can build a custom grant with Authlib for device grant. But I won't put it in the library for now since it is still a draft.

Here is the documentation on custom grant types: http://docs.authlib.org/en/latest/flask/2/grants.html#custom-grant-types

You can also get commercial support from me. Find out at https://authlib.org/support

**Comment by asteven** [comment]
Just for the record.

It seems "OAuth 2.0 Device Authorization Grant" is no longer a draft.
https://datatracker.ietf.org/doc/rfc8628/

**Comment by lepture** [comment]
@asteven rfc8628 is added into plan list

**Comment by lepture** [comment]
Code available in master branch now.

**Comment by asteven** [comment]
Wow! Thanks!
