### ISSUE TITLE
Feature request: Pyramid framework integration

### ISSUE THREAD

**Issue by bjmc** [lepture/authlib#54]
Would be a nice compliment to the Flask and Django integrations.

Pyramid is a good middle ground between the all-singing, all-dancing Django, and the extremely minimalist Flask.

https://trypyramid.com/

**Comment by lepture** [comment]
This library itself will only contain Flask and Django. And they will be moved out of this library when things go stable. That has been said, I build them into the library so that I can design a better API for framework integrations. I think these two are enough for my design.

There is an org for Authlib: https://github.com/authlib I will put other things into the org.

**Comment by lepture** [comment]
Pyramid can have a similar API with Django. I could add it when Authlib turns 1.0.
