### ISSUE TITLE
Session cookie grows indefinitely, results in CSRF Warning.

### ISSUE THREAD

**Issue by frozturk** [lepture/authlib#622]
**Describe the bug**

When session cookie exceeds 4096 bytes, user is getting CSRF Warning.
[set_state_data](https://github.com/lepture/authlib/blob/85f9ff99664bbf0a4f0d043ee807aec08f851f3f/authlib/integrations/base_client/framework_integration.py#L43) assumes cookie can grow indefinitely

**Error**

```
CSRF Warning! State not equal in request and response.'
```

**To Reproduce**

Use SessionMiddleware from starlette, ie. [fastapi demo](https://github.com/authlib/demo-oauth-client/tree/master/fastapi-google-login). Go to login page several times but never login. Eventually set-cookie will try to write more than 4096 bytes, browsers won't save the cookie, resulting in CSRF error because latest state is not in cookie.

**Expected behavior**

A cookie should never exceed 4096 bytes, so users can login without CSRF errors.

**Additional context**

This issue is potentially caused by commit [Refactor whole client integrations. · lepture/authlib@179dc8a](https://github.com/lepture/authlib/commit/179dc8a0d5a9d558709ae952c2ffe9588a84ec62) which were aiming to solve issue [Allowing multiple authentication flows in parallel (e.g., in different tabs) · Issue #285 · lepture/authlib](https://github.com/lepture/authlib/issues/285)

Also see: [Browser Cookie Limits](http://browsercookielimits.iain.guru/): `If you want to support most browsers, then don't exceed 50 cookies per domain, and don't exceed 4093** bytes per domain (i.e. total size of all cookies <= 4093 bytes).`

**Comment by Wauplin** [comment]
Also reporting the same issue. What I did to solve this in our integration (see https://github.com/gradio-app/gradio/pull/8000) is to catch the `MismatchingStateError` when it happens and delete all legacy states from the session cookie.

```py
try:
    oauth_info = await oauth.huggingface.authorize_access_token(request)
except MismatchingStateError:
    # Delete all keys that are related to the OAuth state
    for key in list(request.session.keys()):
        if key.startswith("_state_huggingface"):
            request.session.pop(key)

    # Redirect back to login
    return RedirectResponse(login_uri)
```

Thanks @frozturk when founding out the root cause and hope this snippet will help future users until this bug is fixed.


(Regarding how to fix things in `authlib` itself, I don't know what should be the best approach. A naive solution is to clear previous states when adding a new one but it might cause (minor) discrepancies if a user is working in several tabs. @lepture Happy to open a PR though if this solution looks fine for you.)

**Comment by lepture** [comment]
@Wauplin A PR is welcome. Thank you.

**Comment by Wauplin** [comment]
@lepture I just opened https://github.com/lepture/authlib/pull/644. Please let me know what you think.
